name: Go

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/build.sh
      - name: Test
        run: go test
      - uses: actions/upload-artifact@v4
        with:
          name: godeploy-artifacts
          path: build/*
      - name: Create SSH key
        shell: bash
        run: ./scripts/add-keys.sh ${{ secrets.SSH_KEY }} ${{ secrets.SSH_HOST }}

      - name: Download atrifac
        uses: actions/download-artifact@v4
        with:
          name: godeploy-artifacts
          path: ~/build
      - name: Upload artifacts
        shell: bash
        run: ./scripts/deploy.sh ${{ secrets.SSH_HOST }}


