name: Go

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set envs
        id: envs
        run: echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        run: ./scripts/build.sh
      - name: Test
        run: go test
      - uses: actions/upload-artifact@v4
        with:
          name: godeploy-artifacts
          path: ./build/*

  deploy:
    name: Deploy code
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download atrifac
        uses: actions/download-artifact@v4
        with:
          name: godeploy-artifacts
      - name: Create SSH key
        shell: bash
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
          echo "Host *\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ~/.ssh/id_rsa\n" > ~/.ssh/config
      - name: Upload artifacts
        shell: bash
        run: |
          scp  ./godeploy-artifacts.zip github-ci@${{ secrets.SSH_HOST }}:/~



