name: Go

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/build.sh
      - name: Test
        run: go test
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./build/*