name: Go

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set envs
        id: envs
        run: echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        run: ./scripts/build.sh
      - name: Test
        run: go test


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -rav --delete build/ github-ci@${{ secrets.SSH_HOSTS }}:~


 